@echo off
echo Please wait.....
echo Installing Dot Net V4.8 ....
@echo off
start /w Data\dotnetfx45_full_x86_x64.exe /passive /NoSetupVersionCheck /norestart
echo Dot Net v4.8 installed successfully!
echo Proceeding...
echo Installing FP Capture Express 32 Bit.....
@echo off
start /w msiexec /i Data\FPCapture_ExressLite32bit.msi /passive /norestart
echo FP Capture Express 32 Bit installed successfully!
echo Proceeding...
echo Installing Visual Studio 2012....
start /w Data\vc2012_redist_x86_11.0.60610.1.exe /install /passive /norestart
echo Visual Studio 2012 installed successfully!
echo Proceeding...
echo Installing Virtual Driver FP Capture Access....
start /w Data\VirtualDriver_FPCapture_Access.exe /v/passive /v/norestart
echo Virtual Driver FP Capture Access installed successfully! 
echo Proceeding...
echo Installing  Cognet EndPoint Wrapper....
start /w msiexec /i Cogent.EndPoint.Wrapper.msi /passive /norestart
echo Police Cognet EndPoint Wrapper installed successfully! 
echo The Installation finished, you can close this window and the timer window.
echo Please Restart your computer to fully take effect...
@echo off
pause
